import Head from "next/head";
import Image from "next/image";
import { client } from "../lib/sanity";

interface GalleryPageProps {
  foods: any[];
}

export default function GalleryPage({ foods }: GalleryPageProps) {
  return (
    <div>
      <Head>
        <title>Hearts</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="overflow-hidden text-gray-700 ">
        {foods.length > 0 &&
          foods.map((f, index) => (
            <div
              className="container px-5 py-2 mx-auto lg:pt-12 lg:px-32"
              key={index}
            >
              <div className="text-3xl">{f.name}</div>
              <div className="flex flex-wrap -m-1 md:-m-2">
                {f.images.map((i: any, index: number) => {
                  console.log("i: ", i);
                  return (
                    <div className="flex flex-wrap w-1/3" key={index}>
                      <div className="w-full p-1 md:p-2">
                        <Image
                          alt="gallery"
                          className="block object-cover object-center w-full h-full rounded-lg"
                          src={i.imageUrl}
                          width={320}
                          height={240}
                        />
                      </div>
                    </div>
                  );
                })}
              </div>
            </div>
          ))}
      </section>
    </div>
  );
}

export async function getStaticProps() {
  const foods = await client
    .fetch(
      `*[_type == "foods"]{
  "images": images[]{
   name,
   caption,
   "imageUrl": asset->url
 }
}`
    )
    .catch();

  return {
    props: {
      foods,
    },
  };
}
