import Head from "next/head";
import { useEffect, useState } from "react";
import LunchesGallery from "../components/LunchesGallery";
import { Image } from "../types";

export default function Home() {
  const [lunchesImages, setLunches] = useState<Image[]>([]);
  const [error, setError] = useState<string>("");

  useEffect(() => {
    fetch("/api/getLunches")
      .then(async (res) => {
        if (res.status === 200) {
          const lunches = await res.json();
          console.log("lunches: ", lunches);
          return setLunches(lunches[0].images);
        }

        throw new Error();
      })

      .catch((error) => {
        console.log("Unexpected error occurred: ", error);
        setError("Unexpected Error");
      });
  }, []);

  return (
    <div>
      <Head>
        <title>Hearts</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      {error && (
        <div>
          <p className="text-red-500">Error has occurred</p>
        </div>
      )}

      <LunchesGallery lunches={lunchesImages} />
    </div>
  );
}
