import Head from "next/head";
import { client } from "../sanity";

type Pet = any;
interface HomeProps {
  pets: Pet[];
}

export default function Home({ pets }: HomeProps) {
  return (
    <div>
      <Head>
        <title>Hearts</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-3xl font-bold underline">Hello world!</h1>{" "}
      <main>
        <h2>Pets</h2>
        {pets.length > 0 && (
          <ul>
            {pets.map((pet) => (
              <li key={pet._id}>{pet?.name}</li>
            ))}
          </ul>
        )}
        {pets.length < 0 && <p>No pets to show</p>}
        {pets.length > 0 && (
          <div>
            <pre>{JSON.stringify(pets, null, 2)}</pre>
          </div>
        )}
        {pets.length < 0 && (
          <div>
            <div>¯\_(ツ)_/¯</div>
            <p>
              Your data will show up here when you&apos;ve configured everything
              correctly
            </p>
          </div>
        )}
      </main>
    </div>
  );
}

export async function getStaticProps() {
  const pets = await client.fetch(`*[_type == "animal"]`).catch();

  console.log("pets: ", pets);
  return {
    props: {
      pets,
    },
  };
}
